name: "SENATOROV"

permissions:
  contents: write  # Grant write access to the repository contents

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request_review:
  pull_request_review_comment:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      # Шаг для клонирования репозитория
      - uses: actions/checkout@v4

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # Укажите версию Python, либо используйте матрицу версий

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell

      # Запуск codespell с параметрами
      - name: Run codespell
        run: |
          codespell \
          --ignore-regex='^\s*"image\/(jpeg|png|gif|bmp|tiff)":\s.*' \
          --ignore-regex="[A-Za-z0-9+/]{100,}" \
          --skip="*.js,*.html,*.css,*.svg,*.json,*.png,*.jpg,*.yml,*.yaml" \
          $(git ls-files '*.py' '*.ipynb')
