name: "SENATOROV"

permissions:
  contents: write  # Grant write access to the repository contents
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request_review:
  pull_request_review_comment:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nbqa flake8-variables-names pep8-naming flake8-functions-names
    - name: Flake8
      run: |
        nbqa flake8 --ignore=B018,E203,E501,W291,F821,F401,E402,E121 $(git ls-files '*.py' '*.ipynb')
        flake8 --ignore=B018,E203,E501,W291,F821,F401,E402,E121 $(git ls-files '*.py' '*.ipynb')
