name: SENATOROV
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request_review:
  pull_request_review_comment:
jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: isort/isort-action@v1
      with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort nbqa
    - name: isort
      run: |
        nbqa isort --check --float-to-top $(git ls-files '*.ipynb')
